//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rental_BE
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;

    public partial class OrderList
    {

        public int OrderID { get; set; }
        public string CustName { get; set; }
        public int CarID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime PickUpDate { get; set; }
        public System.DateTime DropOffDate { get; set; }
        public Nullable<decimal> DiscountCode { get; set; }
        public Nullable<decimal> OrderCost { get; set; }

        [IgnoreDataMember]
        public virtual carinventory carinventory { get; set; }
    }
}
